{% set version = "4.8.0" %}

package:
  name: tweepy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tweepy/tweepy-{{ version }}.tar.gz
  sha256: 8ba5774ac1663b09e5fce1b030daf076f2c9b3ddbf2e7e7ea0bae762e3b1fe3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - requests >=2.11.1
    - requests-oauthlib >=0.7.0
    - six >=1.10.0
    - pysocks >=1.5.7

test:
  imports:
    - tweepy

about:
  home: http://www.tweepy.org
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: An easy-to-use Python library for accessing the Twitter API

  doc_url: http://tweepy.readthedocs.io
  dev_url: https://github.com/tweepy/tweepy

extra:
  recipe-maintainers:
    - nikicc
    - ocefpaf
