{% set version = "3.8.0" %}

package:
  name: tweepy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tweepy/tweepy-{{ version }}.tar.gz
  sha256: 8abd828ba51a85a2b5bb7373715d6d3bb32d18ac624e3a4db02e4ef8ab48316b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.11.1
    - requests-oauthlib >=0.7.0
    - six >=1.10.0
    - pysocks >=1.5.7

test:
  imports:
    - tweepy

about:
  home: http://www.tweepy.org
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'An easy-to-use Python library for accessing the Twitter API'

  doc_url: http://tweepy.readthedocs.io
  dev_url: https://github.com/tweepy/tweepy

extra:
  recipe-maintainers:
    - nikicc
    - ocefpaf
