travis:
  secure:
    BINSTAR_TOKEN: irZWHsozPG+H7pr2bRUD7pjCxnjpqRw6nV6yGSakg5R3On0CCAF7jScd+XITdPR7FKWvCfEGh+Vd+Fm98Mg/t/AgZBeglvAiQeVcjiy0YYriN6tyVRw0OK4UUHAiqcWYnV9iDe3NVMepNbSfi3XW/VO+ZfjONFeR1lgmpCq5KjF9gleblGhNcDO45Melx8m/JO4aedtaareCWOa00RiyXsjidWILwZsddXrt5mi2tzAxJXV/nxcHnzEhcTgSSx7gCb0/VuPQ/Jf+t6g8L6Ovb6oNSpmosDjgwnRFtsiIM38mkwggDN7khUlpQhZMCyQN6tHQmh6GitWE7/l8coVilP/jP3bEQARovf84f98KTFnWRSDdio7O/R/9p6BHhGfJPKLrXhik00+8XraFcBrA9Nt5wMJo0CgQ9/drf8Z35Hup8b9JckEU8taHVrGyVrf7slp1iI8nP7oK8sBImV9Pjz1/fGUffTb9FA1+vk5irtn79we4U6v5uqXWydpCN7C0v8lncjM8hQMcBW3W254f40xrKk4gjH7w4FCk0s5JT9Gft74tXRkVkaZT7LHNXnNyNs3OsXRTyvtIVl5rWLuQ/15zvO14fLwEkWZnW+9mjT9PFeRRFYMLg15XICJFoGwcRrXIWpOjJjRhGo0LZDt5xZceKFzw99pR9u7YLWsZS6g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
